### ISSUE TITLE
Thor instalation

### ISSUE THREAD

**Issue by ErhanOnur** [mnot/thor#41]
Hi,

There is a problem with installation. Error description is not giving any clue about the problem. I ma using python 2.7..  I tried 3 installation option given in document :

(1) easy_install thor
(2) pip install thor
(3) python setup.py install

Here are the results:

### **(1)**
erhan@erhan-VirtualBox:~$ sudo easy_install thor
Searching for thor
Reading https://pypi.org/simple/thor/
Downloading https://files.pythonhosted.org/packages/eb/88/fe6e286ea190468623d75fd3b3206fc55a98f6af38292b9f45191486dba7/thor-0.7.3.tar.gz#sha256=a6704bdcf0daca2345fc2a648d40332e9b6940b4e67b09f06fcf37cb07c8f5db
Best match: thor 0.7.3
Processing thor-0.7.3.tar.gz
Writing /tmp/easy_install-RXngwH/thor-0.7.3/setup.cfg
Running thor-0.7.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-RXngwH/thor-0.7.3/egg-dist-tmp-O1Htvo
Traceback (most recent call last):
  File "/usr/local/bin/easy_install", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2316, in main
    **kw
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-RXngwH/thor-0.7.3/setup.py", line 4, in <module>
  File "/tmp/easy_install-RXngwH/thor-0.7.3/thor/__init__.py", line 37, in <module>
  File "/tmp/easy_install-RXngwH/thor-0.7.3/thor/loop.py", line 29
    def __init__(self, loop: 'LoopBase' = None) -> None:
                           ^
SyntaxError: invalid syntax
erhan@erhan-VirtualBox:~$ 

### **(2)**
erhan@erhan-VirtualBox:~/Desktop/thor-master$ sudo pip install thor
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/home/erhan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/erhan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting thor
  Downloading https://files.pythonhosted.org/packages/59/4c/b432aa2e9bd4553a316cd5678dbabe4ed98a1615e8c71b4102b72a2337d3/thor-0.6.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-WqbrP7/thor/setup.py", line 5, in <module>
        import thor
      File "thor/__init__.py", line 37, in <module>
        from thor.loop import run, stop, time, schedule, running, debug
      File "thor/loop.py", line 29
        def __init__(self, loop: 'LoopBase' = None) -> None:
                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-WqbrP7/thor/

### **(3)**
erhan@erhan-VirtualBox:~/Desktop/thor-master$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import thor
  File "/home/erhan/Desktop/thor-master/thor/__init__.py", line 37, in <module>
    from thor.loop import run, stop, time, schedule, running, debug
  File "/home/erhan/Desktop/thor-master/thor/loop.py", line 29
    def __init__(self, loop: 'LoopBase' = None) -> None:
                           ^
SyntaxError: invalid syntax

**Comment by mnot** [comment]
As per the docs, Thor requires Python 3.5 or greater.
